services:
    loevgaard_dandomain_image_optimizer.optimizer:
        class: Loevgaard\DandomainImageOptimizerBundle\Service\Optimizer
        calls:
            - [setContainer, ['@service_container']]